# Generated by Django 4.1.1 on 2022-10-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variatioon_category',
            new_name='variation_category',
        ),
    ]
